### ISSUE TITLE
the error of [pip install -r requirements.txt]

### ISSUE THREAD

**Issue by victor-dl** [baoyukun/superTypist#2]
ERROR: Could not find a version that satisfies the requirement time (from versions: none)
ERROR: No matching distribution found for time

why ?
i had seen the file of requirements.txt 
in the file there 
pygame
argparse
time
re
what are time and re ?
can you help me ?

**Comment by marralesfios** [comment]
@victor-dl They are both built-in libraries. They should not be included in the requirements.txt file, and you should remove them and try again. They are supplied by the standard Python installation.
